using DevExpress.Data.Filtering;
using DevExpress.ExpressApp;
using DevExpress.ExpressApp.EF;
using DevExpress.ExpressApp.Updating;
using DevExpress.Persistent.Base;
using DevExpress.Persistent.BaseImpl.EF;
using gdi3.Module.BusinessObjects;
using Microsoft.Extensions.DependencyInjection;

namespace gdi3.Module.DatabaseUpdate
{
    // For more typical usage scenarios, be sure to check out https://docs.devexpress.com/eXpressAppFramework/DevExpress.ExpressApp.Updating.ModuleUpdater
    public class Updater : ModuleUpdater
    {
        public Updater(IObjectSpace objectSpace, Version currentDBVersion) :
            base(objectSpace, currentDBVersion)
        {
        }
        public override void UpdateDatabaseAfterUpdateSchema()
        {
            base.UpdateDatabaseAfterUpdateSchema();
            InitializeCustomers();
            ObjectSpace.CommitChanges();
        }

        private void InitializeCustomers()
        {
            var customerData = new[]
            {
                ("Alice Johnson",    "alice.johnson@example.com",    "555-0101", "10 Main St, Springfield"),
                ("Bob Smith",        "bob.smith@example.com",        "555-0102", "22 Oak Ave, Shelbyville"),
                ("Carol Williams",   "carol.williams@example.com",   "555-0103", "33 Pine Rd, Capital City"),
                ("David Brown",      "david.brown@example.com",      "555-0104", "44 Elm St, Ogdenville"),
                ("Eva Martinez",     "eva.martinez@example.com",     "555-0105", "55 Maple Dr, North Haverbrook"),
                ("Frank Garcia",     "frank.garcia@example.com",     "555-0106", "66 Cedar Ln, Brockway"),
                ("Grace Lee",        "grace.lee@example.com",        "555-0107", "77 Birch Ct, Cypress Creek"),
                ("Henry Wilson",     "henry.wilson@example.com",     "555-0108", "88 Walnut Way, Shelbyville"),
                ("Irene Taylor",     "irene.taylor@example.com",     "555-0109", "99 Spruce Blvd, Springfield"),
                ("Jack Anderson",    "jack.anderson@example.com",    "555-0110", "110 Ash St, Capital City"),
                ("Karen Thomas",     "karen.thomas@example.com",     "555-0111", "121 Willow Pl, Ogdenville"),
                ("Leo Jackson",      "leo.jackson@example.com",      "555-0112", "132 Poplar Ave, Brockway"),
                ("Mia White",        "mia.white@example.com",        "555-0113", "143 Hickory Dr, Cypress Creek"),
                ("Nathan Harris",    "nathan.harris@example.com",    "555-0114", "154 Chestnut Rd, Springfield"),
                ("Olivia Clark",     "olivia.clark@example.com",     "555-0115", "165 Magnolia St, Shelbyville"),
                ("Paul Lewis",       "paul.lewis@example.com",       "555-0116", "176 Sycamore Ln, Capital City"),
                ("Quinn Robinson",   "quinn.robinson@example.com",   "555-0117", "187 Redwood Ct, Ogdenville"),
                ("Rachel Walker",    "rachel.walker@example.com",    "555-0118", "198 Sequoia Way, North Haverbrook"),
                ("Sam Young",        "sam.young@example.com",        "555-0119", "209 Juniper Blvd, Brockway"),
                ("Tina King",        "tina.king@example.com",        "555-0120", "220 Dogwood Pl, Cypress Creek"),
                ("Uma Patel",        "uma.patel@example.com",        "555-0121", "231 Fir St, Springfield"),
                ("Victor Chen",      "victor.chen@example.com",      "555-0122", "242 Larch Ave, Shelbyville"),
                ("Wendy Brooks",     "wendy.brooks@example.com",     "555-0123", "253 Alder Rd, Capital City"),
                ("Xavier Diaz",      "xavier.diaz@example.com",      "555-0124", "264 Beech St, Ogdenville"),
                ("Yolanda Foster",   "yolanda.foster@example.com",   "555-0125", "275 Cypress Dr, North Haverbrook"),
                ("Zachary Grant",    "zachary.grant@example.com",    "555-0126", "286 Hazel Ln, Brockway"),
                ("Amber Hayes",      "amber.hayes@example.com",     "555-0127", "297 Ivy Ct, Cypress Creek"),
                ("Brian Ingram",     "brian.ingram@example.com",     "555-0128", "308 Jasmine Way, Shelbyville"),
                ("Cynthia James",    "cynthia.james@example.com",   "555-0129", "319 Kalmia Blvd, Springfield"),
                ("Derek Kelly",      "derek.kelly@example.com",      "555-0130", "330 Laurel Pl, Capital City"),
                ("Elena Larson",     "elena.larson@example.com",     "555-0131", "341 Myrtle St, Ogdenville"),
                ("Felix Mitchell",   "felix.mitchell@example.com",   "555-0132", "352 Nettle Ave, Brockway"),
                ("Gina Nelson",      "gina.nelson@example.com",      "555-0133", "363 Olive Rd, Cypress Creek"),
                ("Hugo Owens",       "hugo.owens@example.com",       "555-0134", "374 Palm St, Springfield"),
                ("Isla Perry",       "isla.perry@example.com",       "555-0135", "385 Quince Dr, Shelbyville"),
                ("Jason Quinn",      "jason.quinn@example.com",      "555-0136", "396 Rose Ln, Capital City"),
                ("Kelly Reed",       "kelly.reed@example.com",       "555-0137", "407 Sage Ct, Ogdenville"),
                ("Liam Scott",       "liam.scott@example.com",       "555-0138", "418 Thyme Way, North Haverbrook"),
                ("Monica Turner",    "monica.turner@example.com",    "555-0139", "429 Umber Blvd, Brockway"),
                ("Nolan Underwood",  "nolan.underwood@example.com",  "555-0140", "440 Violet Pl, Cypress Creek"),
                ("Opal Vance",       "opal.vance@example.com",       "555-0141", "451 Wisteria St, Springfield"),
                ("Peter Walsh",      "peter.walsh@example.com",      "555-0142", "462 Xyris Ave, Shelbyville"),
                ("Rhonda York",      "rhonda.york@example.com",      "555-0143", "473 Yarrow Rd, Capital City"),
                ("Steve Zimmerman",  "steve.zimmerman@example.com",  "555-0144", "484 Zinnia St, Ogdenville"),
                ("Tara Abbott",      "tara.abbott@example.com",      "555-0145", "495 Acacia Dr, North Haverbrook"),
                ("Ulrich Baker",     "ulrich.baker@example.com",     "555-0146", "506 Bamboo Ln, Brockway"),
                ("Vera Campbell",    "vera.campbell@example.com",    "555-0147", "517 Clover Ct, Cypress Creek"),
                ("Wayne Davidson",   "wayne.davidson@example.com",   "555-0148", "528 Dahlia Way, Springfield"),
                ("Xena Ellis",       "xena.ellis@example.com",       "555-0149", "539 Eucalyptus Blvd, Shelbyville"),
                ("Yuri Flores",      "yuri.flores@example.com",      "555-0150", "550 Fennel Pl, Capital City"),
                ("Zara Gordon",      "zara.gordon@example.com",      "555-0151", "561 Gardenia St, Ogdenville"),
                ("Adam Harper",      "adam.harper@example.com",      "555-0152", "572 Hemlock Ave, Brockway"),
                ("Bianca Irving",    "bianca.irving@example.com",    "555-0153", "583 Indigo Rd, Cypress Creek"),
                ("Caleb Jensen",     "caleb.jensen@example.com",     "555-0154", "594 Juniper St, Springfield"),
                ("Diana Kemp",       "diana.kemp@example.com",       "555-0155", "605 Kudzu Dr, Shelbyville"),
                ("Ethan Lloyd",      "ethan.lloyd@example.com",      "555-0156", "616 Lilac Ln, Capital City"),
                ("Fiona Marsh",      "fiona.marsh@example.com",      "555-0157", "627 Moss Ct, Ogdenville"),
                ("Grant Newman",     "grant.newman@example.com",     "555-0158", "638 Nutmeg Way, North Haverbrook"),
                ("Holly Ortiz",      "holly.ortiz@example.com",      "555-0159", "649 Orchid Blvd, Brockway"),
                ("Ivan Palmer",      "ivan.palmer@example.com",      "555-0160", "660 Peony Pl, Cypress Creek"),
                ("Julia Quigley",    "julia.quigley@example.com",    "555-0161", "671 Primrose St, Springfield"),
                ("Kurt Ramirez",     "kurt.ramirez@example.com",     "555-0162", "682 Rosemary Ave, Shelbyville"),
                ("Luna Santos",      "luna.santos@example.com",      "555-0163", "693 Sunflower Rd, Capital City"),
                ("Miles Tucker",     "miles.tucker@example.com",     "555-0164", "704 Tamarind St, Ogdenville"),
                ("Nora Upton",       "nora.upton@example.com",       "555-0165", "715 Tulip Dr, North Haverbrook"),
                ("Oscar Valdez",     "oscar.valdez@example.com",     "555-0166", "726 Verbena Ln, Brockway"),
                ("Paige Watkins",    "paige.watkins@example.com",    "555-0167", "737 Willow Ct, Cypress Creek"),
                ("Ruben Xavier",     "ruben.xavier@example.com",     "555-0168", "748 Yew Way, Springfield"),
                ("Selena Young",     "selena.young@example.com",     "555-0169", "759 Azalea Blvd, Shelbyville"),
                ("Troy Ziegler",     "troy.ziegler@example.com",     "555-0170", "770 Basil Pl, Capital City"),
                ("Ursula Adams",     "ursula.adams@example.com",     "555-0171", "781 Camellia St, Ogdenville"),
                ("Vince Barrett",    "vince.barrett@example.com",    "555-0172", "792 Daffodil Ave, Brockway"),
                ("Willa Cruz",       "willa.cruz@example.com",       "555-0173", "803 Elder Rd, Cypress Creek"),
                ("Xander Drake",     "xander.drake@example.com",     "555-0174", "814 Foxglove St, Springfield"),
                ("Yasmin Edwards",   "yasmin.edwards@example.com",   "555-0175", "825 Geranium Dr, Shelbyville"),
                ("Zeke Farrell",     "zeke.farrell@example.com",     "555-0176", "836 Hawthorn Ln, Capital City"),
                ("Alicia Graham",    "alicia.graham@example.com",    "555-0177", "847 Iris Ct, Ogdenville"),
                ("Blake Hoffman",    "blake.hoffman@example.com",    "555-0178", "858 Jonquil Way, North Haverbrook"),
                ("Carmen Ingram",    "carmen.ingram@example.com",    "555-0179", "869 Kentia Blvd, Brockway"),
                ("Dante Jordan",     "dante.jordan@example.com",     "555-0180", "880 Lavender Pl, Cypress Creek"),
                ("Elise Keller",     "elise.keller@example.com",     "555-0181", "891 Magnolia St, Springfield"),
                ("Floyd Lambert",    "floyd.lambert@example.com",    "555-0182", "902 Narcissus Ave, Shelbyville"),
                ("Gloria Mendez",    "gloria.mendez@example.com",    "555-0183", "913 Oleander Rd, Capital City"),
                ("Hank Norris",      "hank.norris@example.com",      "555-0184", "924 Pansy St, Ogdenville"),
                ("Irma Osborne",     "irma.osborne@example.com",     "555-0185", "935 Quassia Dr, North Haverbrook"),
                ("Jared Pike",       "jared.pike@example.com",       "555-0186", "946 Ranunculus Ln, Brockway"),
                ("Kara Quinn",       "kara.quinn@example.com",       "555-0187", "957 Snapdragon Ct, Cypress Creek"),
                ("Lance Rivera",     "lance.rivera@example.com",     "555-0188", "968 Tansy Way, Springfield"),
                ("Maya Sutton",      "maya.sutton@example.com",      "555-0189", "979 Ulex Blvd, Shelbyville"),
                ("Nigel Torres",     "nigel.torres@example.com",     "555-0190", "990 Vetch Pl, Capital City"),
                ("Oona Walsh",       "oona.walsh@example.com",       "555-0191", "1001 Wallflower St, Ogdenville"),
                ("Preston Yates",    "preston.yates@example.com",    "555-0192", "1012 Xylosma Ave, Brockway"),
                ("Queenie Zane",     "queenie.zane@example.com",     "555-0193", "1023 Yucca Rd, Cypress Creek"),
                ("Reuben Adler",     "reuben.adler@example.com",     "555-0194", "1034 Aloe St, Springfield"),
                ("Sonia Brock",      "sonia.brock@example.com",      "555-0195", "1045 Boxwood Dr, Shelbyville"),
                ("Travis Calhoun",   "travis.calhoun@example.com",   "555-0196", "1056 Columbine Ln, Capital City"),
                ("Unity Dawson",     "unity.dawson@example.com",     "555-0197", "1067 Dogwood Ct, Ogdenville"),
                ("Vaughn Ellis",     "vaughn.ellis@example.com",     "555-0198", "1078 Edelweiss Way, North Haverbrook"),
                ("Whitney Frost",    "whitney.frost@example.com",    "555-0199", "1089 Flax Blvd, Brockway"),
                ("Xyla Grant",       "xyla.grant@example.com",       "555-0200", "1100 Gorse Pl, Cypress Creek"),
                ("Yannick Hull",     "yannick.hull@example.com",     "555-0201", "1111 Hosta St, Springfield"),
                ("Zelda Irving",     "zelda.irving@example.com",     "555-0202", "1122 Ixora Ave, Shelbyville"),
                ("Arnold Jacobs",    "arnold.jacobs@example.com",    "555-0203", "1133 Jasmine Rd, Capital City"),
                ("Brenda Kim",       "brenda.kim@example.com",       "555-0204", "1144 Kangaroo St, Ogdenville"),
                ("Clifton Lowe",     "clifton.lowe@example.com",     "555-0205", "1155 Lotus Dr, North Haverbrook"),
                ("Denise Morales",   "denise.morales@example.com",   "555-0206", "1166 Marigold Ln, Brockway"),
                ("Edgar Nash",       "edgar.nash@example.com",       "555-0207", "1177 Nightshade Ct, Cypress Creek"),
                ("Faith Oliver",     "faith.oliver@example.com",     "555-0208", "1188 Oat Way, Springfield"),
                ("Gordon Price",     "gordon.price@example.com",     "555-0209", "1199 Petunia Blvd, Shelbyville"),
                ("Hazel Quinlan",    "hazel.quinlan@example.com",    "555-0210", "1210 Quillwort Pl, Capital City"),
                ("Irving Reese",     "irving.reese@example.com",     "555-0211", "1221 Ragwort St, Ogdenville"),
                ("Joanne Sharp",     "joanne.sharp@example.com",     "555-0212", "1232 Saffron Ave, Brockway"),
                ("Kendrick Tate",    "kendrick.tate@example.com",    "555-0213", "1243 Thistle Rd, Cypress Creek"),
                ("Lena Underhill",   "lena.underhill@example.com",   "555-0214", "1254 Ursinia St, Springfield"),
                ("Martin Voss",      "martin.voss@example.com",      "555-0215", "1265 Valerian Dr, Shelbyville"),
                ("Nadine West",      "nadine.west@example.com",      "555-0216", "1276 Wintergreen Ln, Capital City"),
                ("Otto Xu",          "otto.xu@example.com",          "555-0217", "1287 Wormwood Ct, Ogdenville"),
                ("Penny York",       "penny.york@example.com",       "555-0218", "1298 Yarrow Way, North Haverbrook"),
                ("Quincy Zhu",       "quincy.zhu@example.com",       "555-0219", "1309 Zenobia Blvd, Brockway"),
                ("Rita Albright",    "rita.albright@example.com",     "555-0220", "1320 Amaranth Pl, Cypress Creek"),
                ("Simon Baxter",     "simon.baxter@example.com",     "555-0221", "1 Birch Hill, Lakewood"),
                ("Tammy Conrad",     "tammy.conrad@example.com",     "555-0222", "12 Cedar Crest, Fairview"),
                ("Ulysses Dean",     "ulysses.dean@example.com",     "555-0223", "23 Dogwood Ln, Riverside"),
                ("Violet Emery",     "violet.emery@example.com",     "555-0224", "34 Elm Park, Greendale"),
                ("Walter Finch",     "walter.finch@example.com",     "555-0225", "45 Fern Hollow, Oakmont"),
                ("Ximena Graves",    "ximena.graves@example.com",    "555-0226", "56 Grove Terrace, Pinewood"),
                ("Yosef Hart",       "yosef.hart@example.com",       "555-0227", "67 Holly Ridge, Cedarton"),
                ("Zola Ingersoll",   "zola.ingersoll@example.com",   "555-0228", "78 Ironwood Dr, Maplewood"),
                ("Aiden Judd",       "aiden.judd@example.com",       "555-0229", "89 Juniper Hill, Ashford"),
                ("Bethany Kerr",     "bethany.kerr@example.com",     "555-0230", "100 Kingwood Ave, Elmhurst"),
                ("Carter Lang",      "carter.lang@example.com",      "555-0231", "111 Linden Way, Brookfield"),
                ("Daphne Mercer",    "daphne.mercer@example.com",    "555-0232", "122 Mulberry St, Hazelton"),
                ("Emmet North",      "emmet.north@example.com",      "555-0233", "133 Nuthatch Ln, Willowdale"),
                ("Frida Olsen",      "frida.olsen@example.com",      "555-0234", "144 Oakdale Rd, Birchwood"),
                ("Gavin Pratt",      "gavin.pratt@example.com",      "555-0235", "155 Pinecone Ct, Aldergrove"),
                ("Heidi Rawlins",    "heidi.rawlins@example.com",    "555-0236", "166 Quail Run, Ferndale"),
                ("Isaac Stone",      "isaac.stone@example.com",      "555-0237", "177 Redbird Dr, Sycamore"),
                ("Janet Truong",     "janet.truong@example.com",     "555-0238", "188 Sparrow Ln, Thornton"),
                ("Keith Ulmer",      "keith.ulmer@example.com",      "555-0239", "199 Teal Way, Poplarville"),
                ("Lorraine Vega",    "lorraine.vega@example.com",    "555-0240", "210 Umber Ct, Hickorydale"),
                ("Maxwell Wren",     "maxwell.wren@example.com",     "555-0241", "221 Vine Blvd, Chestnuthill"),
                ("Natasha Xiong",    "natasha.xiong@example.com",    "555-0242", "232 Wren Pl, Aspenridge"),
                ("Orson Yancy",      "orson.yancy@example.com",      "555-0243", "243 Xeric Ave, Tamarackton"),
                ("Priscilla Zook",   "priscilla.zook@example.com",   "555-0244", "254 Yew Hollow, Larchmont"),
                ("Randall Abbott",   "randall.abbott@example.com",   "555-0245", "265 Zinnia Ridge, Sequoiaville"),
                ("Stella Brennan",   "stella.brennan@example.com",   "555-0246", "276 Aster Ln, Juniperdale"),
                ("Terrence Cole",    "terrence.cole@example.com",    "555-0247", "287 Bluebell St, Redwoodton"),
                ("Una Duffy",        "una.duffy@example.com",        "555-0248", "298 Crocus Way, Magnoliaville"),
                ("Vernon Engel",     "vernon.engel@example.com",     "555-0249", "309 Daisy Dr, Hawthornedale"),
                ("Wanda Fischer",    "wanda.fischer@example.com",    "555-0250", "320 Eglantine Ct, Sumacton"),
                ("Xander Gill",      "xander.gill@example.com",      "555-0251", "331 Freesia Blvd, Cloverfield"),
                ("Yvette Hahn",      "yvette.hahn@example.com",      "555-0252", "342 Gentian Pl, Balsam"),
                ("Zander Ibarra",    "zander.ibarra@example.com",    "555-0253", "353 Heather Ave, Sassafrasdale"),
                ("Abigail Jarvis",   "abigail.jarvis@example.com",   "555-0254", "364 Inkberry Rd, Buckeye"),
                ("Brendan Kirk",     "brendan.kirk@example.com",     "555-0255", "375 Jessamine St, Catalpaville"),
                ("Celia Long",       "celia.long@example.com",       "555-0256", "386 Knotweed Dr, Pawpawton"),
                ("Dominic Maxwell",  "dominic.maxwell@example.com",  "555-0257", "397 Larkspur Ln, Persimmon"),
                ("Esther Noble",     "esther.noble@example.com",     "555-0258", "408 Mimosa Ct, Mulberryton"),
                ("Felix Ortega",     "felix.ortega@example.com",     "555-0259", "419 Nightrose Way, Sourwood"),
                ("Genevieve Page",   "genevieve.page@example.com",   "555-0260", "430 Oxlip Blvd, Hophornbeam"),
                ("Harold Quiroz",    "harold.quiroz@example.com",    "555-0261", "441 Phlox Pl, Bayberry"),
                ("Ingrid Russo",     "ingrid.russo@example.com",     "555-0262", "452 Quamash Ave, Beautyberry"),
                ("Joel Sampson",     "joel.sampson@example.com",     "555-0263", "463 Rockrose Rd, Spicebush"),
                ("Kristen Tyson",    "kristen.tyson@example.com",    "555-0264", "474 Starflower St, Wahoo"),
                ("Leonard Unger",    "leonard.unger@example.com",    "555-0265", "485 Trillium Dr, Ninebark"),
                ("Miriam Vail",      "miriam.vail@example.com",      "555-0266", "496 Ursinia Ln, Inkwood"),
                ("Nelson Wolfe",     "nelson.wolfe@example.com",     "555-0267", "507 Viburnum Ct, Leatherleaf"),
                ("Ophelia Yoder",    "ophelia.yoder@example.com",    "555-0268", "518 Woodruff Way, Tanbark"),
                ("Patrick Zane",     "patrick.zane@example.com",     "555-0269", "529 Xeranthemum Blvd, Waxmyrtle"),
                ("Rosalind Ash",     "rosalind.ash@example.com",     "555-0270", "540 Yellowbell Pl, Corkwood"),
                ("Stuart Bond",      "stuart.bond@example.com",      "555-0271", "551 Zenith Ave, Silverbell"),
                ("Tabitha Crane",    "tabitha.crane@example.com",    "555-0272", "562 Aconite Rd, Snowbell"),
                ("Uriel Drake",      "uriel.drake@example.com",      "555-0273", "573 Betony St, Sweetfern"),
                ("Vera Engle",       "vera.engle@example.com",       "555-0274", "584 Campion Dr, Teaberry"),
                ("Wilson Farr",      "wilson.farr@example.com",      "555-0275", "595 Dittany Ln, Witchhazel"),
                ("Xia Garrett",      "xia.garrett@example.com",      "555-0276", "606 Elecampane Ct, Smokewood"),
                ("Yuri Hawkins",     "yuri.hawkins@example.com",     "555-0277", "617 Feverfew Way, Moosewood"),
                ("Zena Ives",        "zena.ives@example.com",        "555-0278", "628 Goldenrod Blvd, Pepperwood"),
                ("Archer Jones",     "archer.jones@example.com",     "555-0279", "639 Hellebore Pl, Hornbeam"),
                ("Blythe Keane",     "blythe.keane@example.com",     "555-0280", "650 Ipheion Ave, Musclewood"),
                ("Conrad Lin",       "conrad.lin@example.com",       "555-0281", "661 Jacobinia Rd, Possumhaw"),
                ("Della Moss",       "della.moss@example.com",       "555-0282", "672 Knapweed St, Butternut"),
                ("Erwin Nash",       "erwin.nash@example.com",       "555-0283", "683 Lungwort Dr, Chinquapin"),
                ("Flora Odom",       "flora.odom@example.com",       "555-0284", "694 Meadowsweet Ln, Hackberry"),
                ("Glenn Parks",      "glenn.parks@example.com",      "555-0285", "705 Navelwort Ct, Hornbeam"),
                ("Hope Randolph",    "hope.randolph@example.com",    "555-0286", "716 Obedience Way, Shadbush"),
                ("Irvin Sparks",     "irvin.sparks@example.com",     "555-0287", "727 Pennywort Blvd, Stewartia"),
                ("Jade Thornton",    "jade.thornton@example.com",    "555-0288", "738 Quassia Pl, Viburnum"),
                ("Keegan Udall",     "keegan.udall@example.com",     "555-0289", "749 Ragweed Ave, Sweetshrub"),
                ("Leona Vargas",     "leona.vargas@example.com",     "555-0290", "760 Silverweed Rd, Witchgrass"),
                ("Morris Whitley",   "morris.whitley@example.com",   "555-0291", "771 Toadflax St, Bittersweet"),
                ("Nelda Xander",     "nelda.xander@example.com",     "555-0292", "782 Upland Dr, Bladderwort"),
                ("Olga Yarbrough",   "olga.yarbrough@example.com",   "555-0293", "793 Vervain Ln, Bugbane"),
                ("Philbert Zook",    "philbert.zook@example.com",    "555-0294", "804 Woundwort Ct, Goatsbeard"),
                ("Quinn Archer",     "quinn.archer@example.com",     "555-0295", "815 Xanthium Way, Snakeroot"),
                ("Renata Bloom",     "renata.bloom@example.com",     "555-0296", "826 Yarrow Blvd, Birthwort"),
                ("Sawyer Clark",     "sawyer.clark@example.com",     "555-0297", "837 Zephyr Pl, Turtlehead"),
                ("Thea Donnelly",    "thea.donnelly@example.com",    "555-0298", "848 Agrimony Ave, Fleabane"),
                ("Ulric Evans",      "ulric.evans@example.com",      "555-0299", "859 Bugloss Rd, Loosestrife"),
                ("Vivian Fuller",    "vivian.fuller@example.com",    "555-0300", "870 Comfrey St, Motherwort"),
                ("Warren Hale",      "warren.hale@example.com",      "555-0301", "881 Dropwort Dr, Scullcap"),
                ("Xyla Jennings",    "xyla.jennings@example.com",    "555-0302", "892 Eyebright Ln, Selfheal"),
                ("Yael Kaufman",     "yael.kaufman@example.com",     "555-0303", "903 Figwort Ct, Speedwell"),
                ("Zita Langley",     "zita.langley@example.com",     "555-0304", "914 Goosegrass Way, Stitchwort"),
                ("Alden Monroe",     "alden.monroe@example.com",     "555-0305", "925 Hawkbit Blvd, Stonecrop"),
                ("Bliss Newton",     "bliss.newton@example.com",     "555-0306", "936 Ivywort Pl, Sundew"),
                ("Cyrus Oakley",     "cyrus.oakley@example.com",     "555-0307", "947 Jaborandi Ave, Tormentil"),
                ("Darla Poe",        "darla.poe@example.com",        "555-0308", "958 Knotgrass Rd, Betony"),
                ("Elton Quade",      "elton.quade@example.com",      "555-0309", "969 Liverwort St, Centaury"),
                ("Freya Rawlings",   "freya.rawlings@example.com",   "555-0310", "980 Mugwort Dr, Clary"),
                ("Grover Sinclair",  "grover.sinclair@example.com",  "555-0311", "991 Nipplewort Ln, Dittany"),
                ("Hester Thorne",    "hester.thorne@example.com",    "555-0312", "1002 Pellitory Ct, Elfdock"),
                ("Ira Ulrich",       "ira.ulrich@example.com",       "555-0313", "1013 Restharrow Way, Felwort"),
                ("Josie Vale",       "josie.vale@example.com",       "555-0314", "1024 Sanicle Blvd, Goutweed"),
                ("Knox Whitaker",    "knox.whitaker@example.com",    "555-0315", "1035 Tormentil Pl, Herb Robert"),
                ("Lyla Xavier",      "lyla.xavier@example.com",      "555-0316", "1046 Vetchling Ave, Lousewort"),
                ("Mason Yee",        "mason.yee@example.com",        "555-0317", "1057 Woodsage Rd, Moschatel"),
                ("Nyla Zander",      "nyla.zander@example.com",      "555-0318", "1068 Alexanders St, Pignut"),
                ("Owen Blake",       "owen.blake@example.com",       "555-0319", "1079 Burnet Dr, Rampion"),
                ("Pearl Cleary",     "pearl.cleary@example.com",     "555-0320", "1090 Cudweed Ln, Soapwort"),
            };
            var i = 0;
            foreach (var (name, email, phone, address) in customerData)
            {
                i++;
                var customer = ObjectSpace.FirstOrDefault<Customer>(c => c.Email == email);
                if (customer == null)
                {
                    customer = ObjectSpace.CreateObject<Customer>();
                    customer.Name = name;
                    customer.Email = email;
                    customer.Phone = phone;
                    customer.Address = address;
                }
                customer.IsCurrent = i % 2 == 0;
            }
        }
        public override void UpdateDatabaseBeforeUpdateSchema()
        {
            base.UpdateDatabaseBeforeUpdateSchema();
        }
    }
}
